const { getProjectName } = require("../lib/app-name")
const { program } = require("commander")
const {
  writeStep,
  writeInfo,
  writeSuccess,
  writeError,
} = require("../lib/write")
const client = require("@sendgrid/client")
const conf = require("../lib/conf")
const configure = require("./configure")
const passwordGenerator = require("generate-password")
const store = require("../lib/store")

program
  .command("sendgrid")
  .description("Setup Sendgrid account")
  .action(setupSendgridAccount)

async function setupSendgridAccount() {
  let projectName = await getProjectName()

  writeStep("Creating Sendgrid subuser")

  let { apiKey } =
    conf.get("sendgrid") || (await configure("sendgrid")).sendgrid

  client.setApiKey(apiKey)

  try {
    const [, ips] = await client.request({
      method: "GET",
      url: "/v3/ips/assigned",
    })

    const ip = ips[0].ip

    /*
    {
      "username": "example_subuser",
      "user_id": 1234,
      "email": "example@example.com",
      "signup_session_token": "",
      "authorization_token": "",
      "credit_allocation": {
        "type": "unlimited"
      }
    }
    */
    const [, subuser] = await client.request({
      method: "POST",
      url: "/v3/subusers",
      body: {
        username: projectName,
        email: `${projectName}@sendgrid.triggerfish.se`,
        password: passwordGenerator.generate({
          numbers: true,
          symbols: true,
        }),
        ips: [ip],
      },
    })

    writeSuccess(`Sendgrid subuser created`)

    writeStep("Creating Sendgrid subuser api key")

    /*
    {
      api_key: "",
      api_key_id: "",
      name: "",
      scopes: [""]
    }
    */
    const [, data] = await client.request({
      method: "POST",
      url: "/v3/api_keys",
      headers: {
        "on-behalf-of": subuser.username,
      },
      body: {
        name: "Web - Generated by Lisa CLI",
        scopes: [
          "mail.batch.create",
          "mail.batch.delete",
          "mail.batch.read",
          "mail.batch.update",
          "mail.send",
        ],
      },
    })

    store.set("sendgridApiKey", data.api_key)

    writeSuccess("Sendgrid subuser api key created")
  } catch (e) {
    console.error(e)
    writeError("Error setting up Sendgrid subuser")
  }
}

module.exports = setupSendgridAccount
